// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/rbac/rbac"
	"github.com/995933447/rbac/rbacserver/handler"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "CheckPerm", handler.RBACHandler.CheckPerm, func() *rbac.CheckPermReq {
		return &rbac.CheckPermReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "ListUserRole", handler.RBACHandler.ListUserRole, func() *rbac.ListUserRoleReq {
		return &rbac.ListUserRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "ListRole", handler.RBACHandler.ListRole, func() *rbac.ListRoleReq {
		return &rbac.ListRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "ListPerm", handler.RBACHandler.ListPerm, func() *rbac.ListPermReq {
		return &rbac.ListPermReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "SetUserRole", handler.RBACHandler.SetUserRole, func() *rbac.SetUserRoleReq {
		return &rbac.SetUserRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "SetRole", handler.RBACHandler.SetRole, func() *rbac.SetRoleReq {
		return &rbac.SetRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "SetPerm", handler.RBACHandler.SetPerm, func() *rbac.SetPermReq {
		return &rbac.SetPermReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "RemoveUserRole", handler.RBACHandler.RemoveUserRole, func() *rbac.RemoveUserRoleReq {
		return &rbac.RemoveUserRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "RemoveRole", handler.RBACHandler.RemoveRole, func() *rbac.RemoveRoleReq {
		return &rbac.RemoveRoleReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(rbac.EasymicroGRPCPbServiceNameRBAC, "RemovePerm", handler.RBACHandler.RemovePerm, func() *rbac.RemovePermReq {
		return &rbac.RemovePermReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
