// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/rbac/rbac"
	"github.com/995933447/rbac/rbacserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	rbac.EasymicroGRPCPbServiceNameRBAC,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	rbac.RegisterRBACServer(server, handler.RBACHandler)
	return nil
}
