// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: rbac.proto

package rbac

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_ErrCodeNil                     ErrCode = 0
	ErrCode_ErrCodePermDeadLoop            ErrCode = 6001
	ErrCode_ErrCodeInvalidParam            ErrCode = 6002
	ErrCode_ErrCodeForbidRemoveNotLeafPerm ErrCode = 6003
	ErrCode_ErrCodeUserRoleExisted         ErrCode = 6004
	ErrCode_ErrCodePermNotFound            ErrCode = 6005
	ErrCode_ErrCodeRoleNotFound            ErrCode = 6006
	ErrCode_ErrCodeUserRoleNotFound        ErrCode = 6007
	ErrCode_ErrCodeNameExisted             ErrCode = 6008
	ErrCode_ErrCodeResourceRouteExisted    ErrCode = 6009
	ErrCode_ErrCodePermUsedByRole          ErrCode = 6010
	ErrCode_ErrCodeRoleUsedByUser          ErrCode = 6011
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrCodeNil",
		6001: "ErrCodePermDeadLoop",
		6002: "ErrCodeInvalidParam",
		6003: "ErrCodeForbidRemoveNotLeafPerm",
		6004: "ErrCodeUserRoleExisted",
		6005: "ErrCodePermNotFound",
		6006: "ErrCodeRoleNotFound",
		6007: "ErrCodeUserRoleNotFound",
		6008: "ErrCodeNameExisted",
		6009: "ErrCodeResourceRouteExisted",
		6010: "ErrCodePermUsedByRole",
		6011: "ErrCodeRoleUsedByUser",
	}
	ErrCode_value = map[string]int32{
		"ErrCodeNil":                     0,
		"ErrCodePermDeadLoop":            6001,
		"ErrCodeInvalidParam":            6002,
		"ErrCodeForbidRemoveNotLeafPerm": 6003,
		"ErrCodeUserRoleExisted":         6004,
		"ErrCodePermNotFound":            6005,
		"ErrCodeRoleNotFound":            6006,
		"ErrCodeUserRoleNotFound":        6007,
		"ErrCodeNameExisted":             6008,
		"ErrCodeResourceRouteExisted":    6009,
		"ErrCodePermUsedByRole":          6010,
		"ErrCodeRoleUsedByUser":          6011,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rbac_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_rbac_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{0}
}

type UserRoleStatus int32

const (
	UserRoleStatus_UserRoleStatusNil    UserRoleStatus = 0
	UserRoleStatus_UserRoleStatusNormal UserRoleStatus = 1 // 正常状态
	UserRoleStatus_UserRoleStatusFrozen UserRoleStatus = 2 // 冻结状态
)

// Enum value maps for UserRoleStatus.
var (
	UserRoleStatus_name = map[int32]string{
		0: "UserRoleStatusNil",
		1: "UserRoleStatusNormal",
		2: "UserRoleStatusFrozen",
	}
	UserRoleStatus_value = map[string]int32{
		"UserRoleStatusNil":    0,
		"UserRoleStatusNormal": 1,
		"UserRoleStatusFrozen": 2,
	}
)

func (x UserRoleStatus) Enum() *UserRoleStatus {
	p := new(UserRoleStatus)
	*p = x
	return p
}

func (x UserRoleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRoleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rbac_proto_enumTypes[1].Descriptor()
}

func (UserRoleStatus) Type() protoreflect.EnumType {
	return &file_rbac_proto_enumTypes[1]
}

func (x UserRoleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRoleStatus.Descriptor instead.
func (UserRoleStatus) EnumDescriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{1}
}

type RoleStatus int32

const (
	RoleStatus_RoleStatusNil    RoleStatus = 0
	RoleStatus_RoleStatusNormal RoleStatus = 1 // 正常状态
	RoleStatus_RoleStatusFrozen RoleStatus = 2 // 冻结状态
)

// Enum value maps for RoleStatus.
var (
	RoleStatus_name = map[int32]string{
		0: "RoleStatusNil",
		1: "RoleStatusNormal",
		2: "RoleStatusFrozen",
	}
	RoleStatus_value = map[string]int32{
		"RoleStatusNil":    0,
		"RoleStatusNormal": 1,
		"RoleStatusFrozen": 2,
	}
)

func (x RoleStatus) Enum() *RoleStatus {
	p := new(RoleStatus)
	*p = x
	return p
}

func (x RoleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rbac_proto_enumTypes[2].Descriptor()
}

func (RoleStatus) Type() protoreflect.EnumType {
	return &file_rbac_proto_enumTypes[2]
}

func (x RoleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleStatus.Descriptor instead.
func (RoleStatus) EnumDescriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{2}
}

type RemovePermReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PermId             uint64                 `protobuf:"varint,1,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	AutoRemoveChildren bool                   `protobuf:"varint,2,opt,name=auto_remove_children,json=autoRemoveChildren,proto3" json:"auto_remove_children,omitempty"`
	AutoUnbindRoles    bool                   `protobuf:"varint,3,opt,name=auto_unbind_roles,json=autoUnbindRoles,proto3" json:"auto_unbind_roles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RemovePermReq) Reset() {
	*x = RemovePermReq{}
	mi := &file_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermReq) ProtoMessage() {}

func (x *RemovePermReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermReq.ProtoReflect.Descriptor instead.
func (*RemovePermReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *RemovePermReq) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *RemovePermReq) GetAutoRemoveChildren() bool {
	if x != nil {
		return x.AutoRemoveChildren
	}
	return false
}

func (x *RemovePermReq) GetAutoUnbindRoles() bool {
	if x != nil {
		return x.AutoUnbindRoles
	}
	return false
}

type RemovePermResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermResp) Reset() {
	*x = RemovePermResp{}
	mi := &file_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermResp) ProtoMessage() {}

func (x *RemovePermResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermResp.ProtoReflect.Descriptor instead.
func (*RemovePermResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{1}
}

type RemoveRoleReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoleId              uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	AutoRemoveUserRoles bool                   `protobuf:"varint,2,opt,name=auto_remove_user_roles,json=autoRemoveUserRoles,proto3" json:"auto_remove_user_roles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RemoveRoleReq) Reset() {
	*x = RemoveRoleReq{}
	mi := &file_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleReq) ProtoMessage() {}

func (x *RemoveRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleReq.ProtoReflect.Descriptor instead.
func (*RemoveRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRoleReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RemoveRoleReq) GetAutoRemoveUserRoles() bool {
	if x != nil {
		return x.AutoRemoveUserRoles
	}
	return false
}

type RemoveRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleResp) Reset() {
	*x = RemoveRoleResp{}
	mi := &file_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleResp) ProtoMessage() {}

func (x *RemoveRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleResp.ProtoReflect.Descriptor instead.
func (*RemoveRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{3}
}

type RemoveUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleReq) Reset() {
	*x = RemoveUserRoleReq{}
	mi := &file_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleReq) ProtoMessage() {}

func (x *RemoveUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleReq.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveUserRoleReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveUserRoleReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RemoveUserRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRoleResp) Reset() {
	*x = RemoveUserRoleResp{}
	mi := &file_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRoleResp) ProtoMessage() {}

func (x *RemoveUserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRoleResp.ProtoReflect.Descriptor instead.
func (*RemoveUserRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{5}
}

type SetPermReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perm          *Perm                  `protobuf:"bytes,1,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPermReq) Reset() {
	*x = SetPermReq{}
	mi := &file_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermReq) ProtoMessage() {}

func (x *SetPermReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermReq.ProtoReflect.Descriptor instead.
func (*SetPermReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *SetPermReq) GetPerm() *Perm {
	if x != nil {
		return x.Perm
	}
	return nil
}

type SetPermResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermId        uint64                 `protobuf:"varint,1,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPermResp) Reset() {
	*x = SetPermResp{}
	mi := &file_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermResp) ProtoMessage() {}

func (x *SetPermResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermResp.ProtoReflect.Descriptor instead.
func (*SetPermResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *SetPermResp) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

type SetRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleReq) Reset() {
	*x = SetRoleReq{}
	mi := &file_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleReq) ProtoMessage() {}

func (x *SetRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleReq.ProtoReflect.Descriptor instead.
func (*SetRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *SetRoleReq) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type SetRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleResp) Reset() {
	*x = SetRoleResp{}
	mi := &file_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleResp) ProtoMessage() {}

func (x *SetRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleResp.ProtoReflect.Descriptor instead.
func (*SetRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *SetRoleResp) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type SetUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      *UserRole              `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRoleReq) Reset() {
	*x = SetUserRoleReq{}
	mi := &file_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRoleReq) ProtoMessage() {}

func (x *SetUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRoleReq.ProtoReflect.Descriptor instead.
func (*SetUserRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *SetUserRoleReq) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

func (x *SetUserRoleReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetUserRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRoleResp) Reset() {
	*x = SetUserRoleResp{}
	mi := &file_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRoleResp) ProtoMessage() {}

func (x *SetUserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRoleResp.ProtoReflect.Descriptor instead.
func (*SetUserRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *SetUserRoleResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      *UserRole              `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleReq) Reset() {
	*x = AddUserRoleReq{}
	mi := &file_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleReq) ProtoMessage() {}

func (x *AddUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleReq.ProtoReflect.Descriptor instead.
func (*AddUserRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *AddUserRoleReq) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

type AddUserRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRoleResp) Reset() {
	*x = AddUserRoleResp{}
	mi := &file_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRoleResp) ProtoMessage() {}

func (x *AddUserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRoleResp.ProtoReflect.Descriptor instead.
func (*AddUserRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{13}
}

type AddRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleReq) Reset() {
	*x = AddRoleReq{}
	mi := &file_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleReq) ProtoMessage() {}

func (x *AddRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleReq.ProtoReflect.Descriptor instead.
func (*AddRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *AddRoleReq) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type AddRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleResp) Reset() {
	*x = AddRoleResp{}
	mi := &file_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleResp) ProtoMessage() {}

func (x *AddRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleResp.ProtoReflect.Descriptor instead.
func (*AddRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{15}
}

type AddPermReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Perm          *Perm                  `protobuf:"bytes,1,opt,name=perm,proto3" json:"perm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPermReq) Reset() {
	*x = AddPermReq{}
	mi := &file_rbac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermReq) ProtoMessage() {}

func (x *AddPermReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermReq.ProtoReflect.Descriptor instead.
func (*AddPermReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{16}
}

func (x *AddPermReq) GetPerm() *Perm {
	if x != nil {
		return x.Perm
	}
	return nil
}

type AddPermResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPermResp) Reset() {
	*x = AddPermResp{}
	mi := &file_rbac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermResp) ProtoMessage() {}

func (x *AddPermResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermResp.ProtoReflect.Descriptor instead.
func (*AddPermResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{17}
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_rbac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{18}
}

func (x *Page) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListPermReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	AllScope      bool                   `protobuf:"varint,4,opt,name=all_scope,json=allScope,proto3" json:"all_scope,omitempty"`
	PermId        uint64                 `protobuf:"varint,5,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`
	Pid           uint64                 `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermReq) Reset() {
	*x = ListPermReq{}
	mi := &file_rbac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermReq) ProtoMessage() {}

func (x *ListPermReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermReq.ProtoReflect.Descriptor instead.
func (*ListPermReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{19}
}

func (x *ListPermReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPermReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListPermReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListPermReq) GetAllScope() bool {
	if x != nil {
		return x.AllScope
	}
	return false
}

func (x *ListPermReq) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *ListPermReq) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type ListPermResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*Perm                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermResp) Reset() {
	*x = ListPermResp{}
	mi := &file_rbac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermResp) ProtoMessage() {}

func (x *ListPermResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermResp.ProtoReflect.Descriptor instead.
func (*ListPermResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{20}
}

func (x *ListPermResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPermResp) GetList() []*Perm {
	if x != nil {
		return x.List
	}
	return nil
}

type ListUserRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	AllScope      bool                   `protobuf:"varint,3,opt,name=all_scope,json=allScope,proto3" json:"all_scope,omitempty"`
	Status        uint64                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	UserId        uint64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        uint64                 `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoleReq) Reset() {
	*x = ListUserRoleReq{}
	mi := &file_rbac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleReq) ProtoMessage() {}

func (x *ListUserRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleReq.ProtoReflect.Descriptor instead.
func (*ListUserRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{21}
}

func (x *ListUserRoleReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListUserRoleReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListUserRoleReq) GetAllScope() bool {
	if x != nil {
		return x.AllScope
	}
	return false
}

func (x *ListUserRoleReq) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUserRoleReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserRoleReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ListUserRoleResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         uint32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*ListUserRoleResp_Item `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoleResp) Reset() {
	*x = ListUserRoleResp{}
	mi := &file_rbac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleResp) ProtoMessage() {}

func (x *ListUserRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleResp.ProtoReflect.Descriptor instead.
func (*ListUserRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{22}
}

func (x *ListUserRoleResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserRoleResp) GetList() []*ListUserRoleResp_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type ListRoleReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Page              *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope             string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	AllScope          bool                   `protobuf:"varint,4,opt,name=all_scope,json=allScope,proto3" json:"all_scope,omitempty"`
	RoleIds           []uint64               `protobuf:"varint,5,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Status            int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	OnlySuperAdmin    bool                   `protobuf:"varint,7,opt,name=only_super_admin,json=onlySuperAdmin,proto3" json:"only_super_admin,omitempty"`
	WithoutSuperAdmin bool                   `protobuf:"varint,8,opt,name=without_super_admin,json=withoutSuperAdmin,proto3" json:"without_super_admin,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRoleReq) Reset() {
	*x = ListRoleReq{}
	mi := &file_rbac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleReq) ProtoMessage() {}

func (x *ListRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleReq.ProtoReflect.Descriptor instead.
func (*ListRoleReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{23}
}

func (x *ListRoleReq) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRoleReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListRoleReq) GetAllScope() bool {
	if x != nil {
		return x.AllScope
	}
	return false
}

func (x *ListRoleReq) GetRoleIds() []uint64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *ListRoleReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListRoleReq) GetOnlySuperAdmin() bool {
	if x != nil {
		return x.OnlySuperAdmin
	}
	return false
}

func (x *ListRoleReq) GetWithoutSuperAdmin() bool {
	if x != nil {
		return x.WithoutSuperAdmin
	}
	return false
}

type ListRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*Role                `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResp) Reset() {
	*x = ListRoleResp{}
	mi := &file_rbac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResp) ProtoMessage() {}

func (x *ListRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResp.ProtoReflect.Descriptor instead.
func (*ListRoleResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{24}
}

func (x *ListRoleResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRoleResp) GetList() []*Role {
	if x != nil {
		return x.List
	}
	return nil
}

type CheckPermReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`                                            // 权限应用域
	UserId          uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                           // 用户id
	ResourceService string                 `protobuf:"bytes,3,opt,name=resource_service,json=resourceService,proto3" json:"resource_service,omitempty"` // 需要访问的服务端路由
	ResourceRoute   string                 `protobuf:"bytes,4,opt,name=resource_route,json=resourceRoute,proto3" json:"resource_route,omitempty"`       // 资源对象，通常代表前端的页面或者按钮等
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckPermReq) Reset() {
	*x = CheckPermReq{}
	mi := &file_rbac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermReq) ProtoMessage() {}

func (x *CheckPermReq) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermReq.ProtoReflect.Descriptor instead.
func (*CheckPermReq) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{25}
}

func (x *CheckPermReq) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CheckPermReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermReq) GetResourceService() string {
	if x != nil {
		return x.ResourceService
	}
	return ""
}

func (x *CheckPermReq) GetResourceRoute() string {
	if x != nil {
		return x.ResourceRoute
	}
	return ""
}

type CheckPermResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rejected      bool                   `protobuf:"varint,1,opt,name=rejected,proto3" json:"rejected,omitempty"` // 是否无权访问
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermResp) Reset() {
	*x = CheckPermResp{}
	mi := &file_rbac_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermResp) ProtoMessage() {}

func (x *CheckPermResp) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermResp.ProtoReflect.Descriptor instead.
func (*CheckPermResp) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{26}
}

func (x *CheckPermResp) GetRejected() bool {
	if x != nil {
		return x.Rejected
	}
	return false
}

type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户id
	RoleId        uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色id
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`               // 状态，参考enum UserRoleStatus
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`                  // 权限应用域，数据根据作用域可以被划分为不同的应用，相同域的数据在同一套rbac规则内，，如使用"corp_op"和"user_op"区分商户后台和用户系统的权限管理
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_rbac_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{27}
}

func (x *UserRole) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRole) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UserRole) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserRole) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                     // 角色id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                        // 角色名称
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态，参考enum RoleStatus
	PermIds       []uint64               `protobuf:"varint,4,rep,packed,name=perm_ids,json=permIds,proto3" json:"perm_ids,omitempty"`           // 权限id
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`                                    // 备注
	Scope         string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`                                      // 权限应用域，数据根据作用域可以被划分为不同的应用，相同域的数据在同一套rbac规则内，，如使用"corp_op"和"user_op"区分商户后台和用户系统的权限管理
	IsSuperAdmin  bool                   `protobuf:"varint,7,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"` // 是否超级管理员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_rbac_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{28}
}

func (x *Role) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Role) GetPermIds() []uint64 {
	if x != nil {
		return x.PermIds
	}
	return nil
}

func (x *Role) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Role) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Role) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

type Perm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PermId           uint64                 `protobuf:"varint,1,opt,name=perm_id,json=permId,proto3" json:"perm_id,omitempty"`                              // 权限id
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                 // 权限名称
	ResourceRoute    string                 `protobuf:"bytes,3,opt,name=resource_route,json=resourceRoute,proto3" json:"resource_route,omitempty"`          // 可访问的资源路径,可以是任意字符串,通用用于代表前端表示,如页面或者按钮或者菜单等
	ResourceServices []*ResourceService     `protobuf:"bytes,4,rep,name=resource_services,json=resourceServices,proto3" json:"resource_services,omitempty"` // 可访问的资源服务,通常代表访问的后端标识,如api.是一个列表,通常一个前端路径对应多个接口
	Scope            string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`                                               // 权限应用域，任意标识字符串,数据根据作用域可以被划分为不同的应用,相同域的数据在同一套rbac规则内,如使用"corp_op"和"user_op"区分商户后台和用户系统的权限管理
	Pid              uint64                 `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`                                                  // 父级菜单id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Perm) Reset() {
	*x = Perm{}
	mi := &file_rbac_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Perm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perm) ProtoMessage() {}

func (x *Perm) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perm.ProtoReflect.Descriptor instead.
func (*Perm) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{29}
}

func (x *Perm) GetPermId() uint64 {
	if x != nil {
		return x.PermId
	}
	return 0
}

func (x *Perm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Perm) GetResourceRoute() string {
	if x != nil {
		return x.ResourceRoute
	}
	return ""
}

func (x *Perm) GetResourceServices() []*ResourceService {
	if x != nil {
		return x.ResourceServices
	}
	return nil
}

func (x *Perm) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Perm) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// 资源服务,通常代表后端标识,如api名称或者api路径等
type ResourceService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // 服务字符串标识,可用api名称或者api路径标识
	Extra         string                 `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`     // 存储一些扩展额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceService) Reset() {
	*x = ResourceService{}
	mi := &file_rbac_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceService) ProtoMessage() {}

func (x *ResourceService) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceService.ProtoReflect.Descriptor instead.
func (*ResourceService) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{30}
}

func (x *ResourceService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ResourceService) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type ListUserRoleResp_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRole      *UserRole              `protobuf:"bytes,1,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoleResp_Item) Reset() {
	*x = ListUserRoleResp_Item{}
	mi := &file_rbac_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoleResp_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoleResp_Item) ProtoMessage() {}

func (x *ListUserRoleResp_Item) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoleResp_Item.ProtoReflect.Descriptor instead.
func (*ListUserRoleResp_Item) Descriptor() ([]byte, []int) {
	return file_rbac_proto_rawDescGZIP(), []int{22, 0}
}

func (x *ListUserRoleResp_Item) GetUserRole() *UserRole {
	if x != nil {
		return x.UserRole
	}
	return nil
}

func (x *ListUserRoleResp_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rbac_proto protoreflect.FileDescriptor

const file_rbac_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rbac.proto\x12\x04rbac\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"\x86\x01\n" +
	"\rRemovePermReq\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\x04R\x06permId\x120\n" +
	"\x14auto_remove_children\x18\x02 \x01(\bR\x12autoRemoveChildren\x12*\n" +
	"\x11auto_unbind_roles\x18\x03 \x01(\bR\x0fautoUnbindRoles\"\x10\n" +
	"\x0eRemovePermResp\"]\n" +
	"\rRemoveRoleReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x123\n" +
	"\x16auto_remove_user_roles\x18\x02 \x01(\bR\x13autoRemoveUserRoles\"\x10\n" +
	"\x0eRemoveRoleResp\"E\n" +
	"\x11RemoveUserRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId\"\x14\n" +
	"\x12RemoveUserRoleResp\",\n" +
	"\n" +
	"SetPermReq\x12\x1e\n" +
	"\x04perm\x18\x01 \x01(\v2\n" +
	".rbac.PermR\x04perm\"&\n" +
	"\vSetPermResp\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\x04R\x06permId\",\n" +
	"\n" +
	"SetRoleReq\x12\x1e\n" +
	"\x04role\x18\x01 \x01(\v2\n" +
	".rbac.RoleR\x04role\"&\n" +
	"\vSetRoleResp\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\"M\n" +
	"\x0eSetUserRoleReq\x12+\n" +
	"\tuser_role\x18\x01 \x01(\v2\x0e.rbac.UserRoleR\buserRole\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"!\n" +
	"\x0fSetUserRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x0eAddUserRoleReq\x12+\n" +
	"\tuser_role\x18\x01 \x01(\v2\x0e.rbac.UserRoleR\buserRole\"\x11\n" +
	"\x0fAddUserRoleResp\",\n" +
	"\n" +
	"AddRoleReq\x12\x1e\n" +
	"\x04role\x18\x01 \x01(\v2\n" +
	".rbac.RoleR\x04role\"\r\n" +
	"\vAddRoleResp\",\n" +
	"\n" +
	"AddPermReq\x12\x1e\n" +
	"\x04perm\x18\x01 \x01(\v2\n" +
	".rbac.PermR\x04perm\"\r\n" +
	"\vAddPermResp\"7\n" +
	"\x04Page\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\"\x9f\x01\n" +
	"\vListPermReq\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\v2\n" +
	".rbac.PageR\x04page\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1b\n" +
	"\tall_scope\x18\x04 \x01(\bR\ballScope\x12\x17\n" +
	"\aperm_id\x18\x05 \x01(\x04R\x06permId\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x04R\x03pid\"D\n" +
	"\fListPermResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x1e\n" +
	"\x04list\x18\x02 \x03(\v2\n" +
	".rbac.PermR\x04list\"\xae\x01\n" +
	"\x0fListUserRoleReq\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\v2\n" +
	".rbac.PageR\x04page\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1b\n" +
	"\tall_scope\x18\x03 \x01(\bR\ballScope\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x04R\x06status\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userId\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\x04R\x06roleId\"\x9e\x01\n" +
	"\x10ListUserRoleResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.rbac.ListUserRoleResp.ItemR\x04list\x1aC\n" +
	"\x04Item\x12+\n" +
	"\tuser_role\x18\x01 \x01(\v2\x0e.rbac.UserRoleR\buserRole\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x81\x02\n" +
	"\vListRoleReq\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\v2\n" +
	".rbac.PageR\x04page\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1b\n" +
	"\tall_scope\x18\x04 \x01(\bR\ballScope\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\x04R\aroleIds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12(\n" +
	"\x10only_super_admin\x18\a \x01(\bR\x0eonlySuperAdmin\x12.\n" +
	"\x13without_super_admin\x18\b \x01(\bR\x11withoutSuperAdmin\"D\n" +
	"\fListRoleResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x1e\n" +
	"\x04list\x18\x02 \x03(\v2\n" +
	".rbac.RoleR\x04list\"\x8f\x01\n" +
	"\fCheckPermReq\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12)\n" +
	"\x10resource_service\x18\x03 \x01(\tR\x0fresourceService\x12%\n" +
	"\x0eresource_route\x18\x04 \x01(\tR\rresourceRoute\"+\n" +
	"\rCheckPermResp\x12\x1a\n" +
	"\brejected\x18\x01 \x01(\bR\brejected\"\xa8\x01\n" +
	"\bUserRole\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope:<\x8a\x8e%8\n" +
	"\x04rbac\x12\x04rbac\x1a\tuser_role*\x05scope*\arole_id:\x0fuser_id,role_id\"\xf4\x01\n" +
	"\x04Role\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x19\n" +
	"\bperm_ids\x18\x04 \x03(\x04R\apermIds\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12$\n" +
	"\x0eis_super_admin\x18\a \x01(\bR\fisSuperAdmin:8\x8a\x8e%4\n" +
	"\x04rbac\x12\x04rbac\x1a\x04role*\x05scope*\x04name:\arole_id:\n" +
	"scope,name\"\xb3\x02\n" +
	"\x04Perm\x12\x17\n" +
	"\aperm_id\x18\x01 \x01(\x04R\x06permId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eresource_route\x18\x03 \x01(\tR\rresourceRoute\x12B\n" +
	"\x11resource_services\x18\x04 \x03(\v2\x15.rbac.ResourceServiceR\x10resourceServices\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x04R\x03pid:k\x8a\x8e%g\n" +
	"\x04rbac\x12\x04rbac\x1a\x04perm*\x05scope*\x04name*\x03pid:\aperm_id:\x16perm_id,resource_route:\x14scope,resource_route:\n" +
	"scope,name\"J\n" +
	"\x0fResourceService\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05extra\x18\x02 \x01(\tR\x05extra:\a\x8a\x8e%\x03\x80\x01\x01*\xd4\x02\n" +
	"\aErrCode\x12\x0e\n" +
	"\n" +
	"ErrCodeNil\x10\x00\x12\x18\n" +
	"\x13ErrCodePermDeadLoop\x10\xf1.\x12\x18\n" +
	"\x13ErrCodeInvalidParam\x10\xf2.\x12#\n" +
	"\x1eErrCodeForbidRemoveNotLeafPerm\x10\xf3.\x12\x1b\n" +
	"\x16ErrCodeUserRoleExisted\x10\xf4.\x12\x18\n" +
	"\x13ErrCodePermNotFound\x10\xf5.\x12\x18\n" +
	"\x13ErrCodeRoleNotFound\x10\xf6.\x12\x1c\n" +
	"\x17ErrCodeUserRoleNotFound\x10\xf7.\x12\x17\n" +
	"\x12ErrCodeNameExisted\x10\xf8.\x12 \n" +
	"\x1bErrCodeResourceRouteExisted\x10\xf9.\x12\x1a\n" +
	"\x15ErrCodePermUsedByRole\x10\xfa.\x12\x1a\n" +
	"\x15ErrCodeRoleUsedByUser\x10\xfb.*[\n" +
	"\x0eUserRoleStatus\x12\x15\n" +
	"\x11UserRoleStatusNil\x10\x00\x12\x18\n" +
	"\x14UserRoleStatusNormal\x10\x01\x12\x18\n" +
	"\x14UserRoleStatusFrozen\x10\x02*K\n" +
	"\n" +
	"RoleStatus\x12\x11\n" +
	"\rRoleStatusNil\x10\x00\x12\x14\n" +
	"\x10RoleStatusNormal\x10\x01\x12\x14\n" +
	"\x10RoleStatusFrozen\x10\x022\xb4\x04\n" +
	"\x04RBAC\x124\n" +
	"\tCheckPerm\x12\x12.rbac.CheckPermReq\x1a\x13.rbac.CheckPermResp\x12=\n" +
	"\fListUserRole\x12\x15.rbac.ListUserRoleReq\x1a\x16.rbac.ListUserRoleResp\x121\n" +
	"\bListRole\x12\x11.rbac.ListRoleReq\x1a\x12.rbac.ListRoleResp\x121\n" +
	"\bListPerm\x12\x11.rbac.ListPermReq\x1a\x12.rbac.ListPermResp\x12:\n" +
	"\vSetUserRole\x12\x14.rbac.SetUserRoleReq\x1a\x15.rbac.SetUserRoleResp\x12.\n" +
	"\aSetRole\x12\x10.rbac.SetRoleReq\x1a\x11.rbac.SetRoleResp\x12.\n" +
	"\aSetPerm\x12\x10.rbac.SetPermReq\x1a\x11.rbac.SetPermResp\x12C\n" +
	"\x0eRemoveUserRole\x12\x17.rbac.RemoveUserRoleReq\x1a\x18.rbac.RemoveUserRoleResp\x127\n" +
	"\n" +
	"RemoveRole\x12\x13.rbac.RemoveRoleReq\x1a\x14.rbac.RemoveRoleResp\x127\n" +
	"\n" +
	"RemovePerm\x12\x13.rbac.RemovePermReq\x1a\x14.rbac.RemovePermRespB0\x8a\x9d \fZ\x04rbacb\x04rbacZ\x1egithub.com/995933447/rbac/rbacb\x06proto3"

var (
	file_rbac_proto_rawDescOnce sync.Once
	file_rbac_proto_rawDescData []byte
)

func file_rbac_proto_rawDescGZIP() []byte {
	file_rbac_proto_rawDescOnce.Do(func() {
		file_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rbac_proto_rawDesc), len(file_rbac_proto_rawDesc)))
	})
	return file_rbac_proto_rawDescData
}

var file_rbac_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_rbac_proto_goTypes = []any{
	(ErrCode)(0),                  // 0: rbac.ErrCode
	(UserRoleStatus)(0),           // 1: rbac.UserRoleStatus
	(RoleStatus)(0),               // 2: rbac.RoleStatus
	(*RemovePermReq)(nil),         // 3: rbac.RemovePermReq
	(*RemovePermResp)(nil),        // 4: rbac.RemovePermResp
	(*RemoveRoleReq)(nil),         // 5: rbac.RemoveRoleReq
	(*RemoveRoleResp)(nil),        // 6: rbac.RemoveRoleResp
	(*RemoveUserRoleReq)(nil),     // 7: rbac.RemoveUserRoleReq
	(*RemoveUserRoleResp)(nil),    // 8: rbac.RemoveUserRoleResp
	(*SetPermReq)(nil),            // 9: rbac.SetPermReq
	(*SetPermResp)(nil),           // 10: rbac.SetPermResp
	(*SetRoleReq)(nil),            // 11: rbac.SetRoleReq
	(*SetRoleResp)(nil),           // 12: rbac.SetRoleResp
	(*SetUserRoleReq)(nil),        // 13: rbac.SetUserRoleReq
	(*SetUserRoleResp)(nil),       // 14: rbac.SetUserRoleResp
	(*AddUserRoleReq)(nil),        // 15: rbac.AddUserRoleReq
	(*AddUserRoleResp)(nil),       // 16: rbac.AddUserRoleResp
	(*AddRoleReq)(nil),            // 17: rbac.AddRoleReq
	(*AddRoleResp)(nil),           // 18: rbac.AddRoleResp
	(*AddPermReq)(nil),            // 19: rbac.AddPermReq
	(*AddPermResp)(nil),           // 20: rbac.AddPermResp
	(*Page)(nil),                  // 21: rbac.Page
	(*ListPermReq)(nil),           // 22: rbac.ListPermReq
	(*ListPermResp)(nil),          // 23: rbac.ListPermResp
	(*ListUserRoleReq)(nil),       // 24: rbac.ListUserRoleReq
	(*ListUserRoleResp)(nil),      // 25: rbac.ListUserRoleResp
	(*ListRoleReq)(nil),           // 26: rbac.ListRoleReq
	(*ListRoleResp)(nil),          // 27: rbac.ListRoleResp
	(*CheckPermReq)(nil),          // 28: rbac.CheckPermReq
	(*CheckPermResp)(nil),         // 29: rbac.CheckPermResp
	(*UserRole)(nil),              // 30: rbac.UserRole
	(*Role)(nil),                  // 31: rbac.Role
	(*Perm)(nil),                  // 32: rbac.Perm
	(*ResourceService)(nil),       // 33: rbac.ResourceService
	(*ListUserRoleResp_Item)(nil), // 34: rbac.ListUserRoleResp.Item
}
var file_rbac_proto_depIdxs = []int32{
	32, // 0: rbac.SetPermReq.perm:type_name -> rbac.Perm
	31, // 1: rbac.SetRoleReq.role:type_name -> rbac.Role
	30, // 2: rbac.SetUserRoleReq.user_role:type_name -> rbac.UserRole
	30, // 3: rbac.AddUserRoleReq.user_role:type_name -> rbac.UserRole
	31, // 4: rbac.AddRoleReq.role:type_name -> rbac.Role
	32, // 5: rbac.AddPermReq.perm:type_name -> rbac.Perm
	21, // 6: rbac.ListPermReq.page:type_name -> rbac.Page
	32, // 7: rbac.ListPermResp.list:type_name -> rbac.Perm
	21, // 8: rbac.ListUserRoleReq.page:type_name -> rbac.Page
	34, // 9: rbac.ListUserRoleResp.list:type_name -> rbac.ListUserRoleResp.Item
	21, // 10: rbac.ListRoleReq.page:type_name -> rbac.Page
	31, // 11: rbac.ListRoleResp.list:type_name -> rbac.Role
	33, // 12: rbac.Perm.resource_services:type_name -> rbac.ResourceService
	30, // 13: rbac.ListUserRoleResp.Item.user_role:type_name -> rbac.UserRole
	28, // 14: rbac.RBAC.CheckPerm:input_type -> rbac.CheckPermReq
	24, // 15: rbac.RBAC.ListUserRole:input_type -> rbac.ListUserRoleReq
	26, // 16: rbac.RBAC.ListRole:input_type -> rbac.ListRoleReq
	22, // 17: rbac.RBAC.ListPerm:input_type -> rbac.ListPermReq
	13, // 18: rbac.RBAC.SetUserRole:input_type -> rbac.SetUserRoleReq
	11, // 19: rbac.RBAC.SetRole:input_type -> rbac.SetRoleReq
	9,  // 20: rbac.RBAC.SetPerm:input_type -> rbac.SetPermReq
	7,  // 21: rbac.RBAC.RemoveUserRole:input_type -> rbac.RemoveUserRoleReq
	5,  // 22: rbac.RBAC.RemoveRole:input_type -> rbac.RemoveRoleReq
	3,  // 23: rbac.RBAC.RemovePerm:input_type -> rbac.RemovePermReq
	29, // 24: rbac.RBAC.CheckPerm:output_type -> rbac.CheckPermResp
	25, // 25: rbac.RBAC.ListUserRole:output_type -> rbac.ListUserRoleResp
	27, // 26: rbac.RBAC.ListRole:output_type -> rbac.ListRoleResp
	23, // 27: rbac.RBAC.ListPerm:output_type -> rbac.ListPermResp
	14, // 28: rbac.RBAC.SetUserRole:output_type -> rbac.SetUserRoleResp
	12, // 29: rbac.RBAC.SetRole:output_type -> rbac.SetRoleResp
	10, // 30: rbac.RBAC.SetPerm:output_type -> rbac.SetPermResp
	8,  // 31: rbac.RBAC.RemoveUserRole:output_type -> rbac.RemoveUserRoleResp
	6,  // 32: rbac.RBAC.RemoveRole:output_type -> rbac.RemoveRoleResp
	4,  // 33: rbac.RBAC.RemovePerm:output_type -> rbac.RemovePermResp
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_rbac_proto_init() }
func file_rbac_proto_init() {
	if File_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_proto_rawDesc), len(file_rbac_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbac_proto_goTypes,
		DependencyIndexes: file_rbac_proto_depIdxs,
		EnumInfos:         file_rbac_proto_enumTypes,
		MessageInfos:      file_rbac_proto_msgTypes,
	}.Build()
	File_rbac_proto = out.File
	file_rbac_proto_goTypes = nil
	file_rbac_proto_depIdxs = nil
}
