// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: rbac.proto

package rbac

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RBAC_CheckPerm_FullMethodName          = "/rbac.RBAC/CheckPerm"
	RBAC_ListUserRole_FullMethodName       = "/rbac.RBAC/ListUserRole"
	RBAC_ListRole_FullMethodName           = "/rbac.RBAC/ListRole"
	RBAC_ListPerm_FullMethodName           = "/rbac.RBAC/ListPerm"
	RBAC_SetUserRole_FullMethodName        = "/rbac.RBAC/SetUserRole"
	RBAC_OverwriteUserRoles_FullMethodName = "/rbac.RBAC/OverwriteUserRoles"
	RBAC_SetRole_FullMethodName            = "/rbac.RBAC/SetRole"
	RBAC_SetPerm_FullMethodName            = "/rbac.RBAC/SetPerm"
	RBAC_RemoveUserRole_FullMethodName     = "/rbac.RBAC/RemoveUserRole"
	RBAC_RemoveRole_FullMethodName         = "/rbac.RBAC/RemoveRole"
	RBAC_RemovePerm_FullMethodName         = "/rbac.RBAC/RemovePerm"
)

// RBACClient is the client API for RBAC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RBACClient interface {
	// 检查用户是否具有资源或服务端路由的访问权限
	CheckPerm(ctx context.Context, in *CheckPermReq, opts ...grpc.CallOption) (*CheckPermResp, error)
	// 获取用户列表
	ListUserRole(ctx context.Context, in *ListUserRoleReq, opts ...grpc.CallOption) (*ListUserRoleResp, error)
	// 获取角色列表
	ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error)
	// 获取权限列表
	ListPerm(ctx context.Context, in *ListPermReq, opts ...grpc.CallOption) (*ListPermResp, error)
	// 设置用户角色
	SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...grpc.CallOption) (*SetUserRoleResp, error)
	// 批量设置用户角色
	OverwriteUserRoles(ctx context.Context, in *OverwriteUserRolesReq, opts ...grpc.CallOption) (*OverwriteUserRolesResp, error)
	// 设置角色
	SetRole(ctx context.Context, in *SetRoleReq, opts ...grpc.CallOption) (*SetRoleResp, error)
	// 设置菜单
	SetPerm(ctx context.Context, in *SetPermReq, opts ...grpc.CallOption) (*SetPermResp, error)
	// 移除用户角色
	RemoveUserRole(ctx context.Context, in *RemoveUserRoleReq, opts ...grpc.CallOption) (*RemoveUserRoleResp, error)
	// 移除角色
	RemoveRole(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*RemoveRoleResp, error)
	// 移除菜单
	RemovePerm(ctx context.Context, in *RemovePermReq, opts ...grpc.CallOption) (*RemovePermResp, error)
}

type rBACClient struct {
	cc grpc.ClientConnInterface
}

func NewRBACClient(cc grpc.ClientConnInterface) RBACClient {
	return &rBACClient{cc}
}

func (c *rBACClient) CheckPerm(ctx context.Context, in *CheckPermReq, opts ...grpc.CallOption) (*CheckPermResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermResp)
	err := c.cc.Invoke(ctx, RBAC_CheckPerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) ListUserRole(ctx context.Context, in *ListUserRoleReq, opts ...grpc.CallOption) (*ListUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserRoleResp)
	err := c.cc.Invoke(ctx, RBAC_ListUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleResp)
	err := c.cc.Invoke(ctx, RBAC_ListRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) ListPerm(ctx context.Context, in *ListPermReq, opts ...grpc.CallOption) (*ListPermResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermResp)
	err := c.cc.Invoke(ctx, RBAC_ListPerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...grpc.CallOption) (*SetUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserRoleResp)
	err := c.cc.Invoke(ctx, RBAC_SetUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) OverwriteUserRoles(ctx context.Context, in *OverwriteUserRolesReq, opts ...grpc.CallOption) (*OverwriteUserRolesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverwriteUserRolesResp)
	err := c.cc.Invoke(ctx, RBAC_OverwriteUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) SetRole(ctx context.Context, in *SetRoleReq, opts ...grpc.CallOption) (*SetRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoleResp)
	err := c.cc.Invoke(ctx, RBAC_SetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) SetPerm(ctx context.Context, in *SetPermReq, opts ...grpc.CallOption) (*SetPermResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPermResp)
	err := c.cc.Invoke(ctx, RBAC_SetPerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) RemoveUserRole(ctx context.Context, in *RemoveUserRoleReq, opts ...grpc.CallOption) (*RemoveUserRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserRoleResp)
	err := c.cc.Invoke(ctx, RBAC_RemoveUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) RemoveRole(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*RemoveRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRoleResp)
	err := c.cc.Invoke(ctx, RBAC_RemoveRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rBACClient) RemovePerm(ctx context.Context, in *RemovePermReq, opts ...grpc.CallOption) (*RemovePermResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePermResp)
	err := c.cc.Invoke(ctx, RBAC_RemovePerm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RBACServer is the server API for RBAC service.
// All implementations must embed UnimplementedRBACServer
// for forward compatibility.
type RBACServer interface {
	// 检查用户是否具有资源或服务端路由的访问权限
	CheckPerm(context.Context, *CheckPermReq) (*CheckPermResp, error)
	// 获取用户列表
	ListUserRole(context.Context, *ListUserRoleReq) (*ListUserRoleResp, error)
	// 获取角色列表
	ListRole(context.Context, *ListRoleReq) (*ListRoleResp, error)
	// 获取权限列表
	ListPerm(context.Context, *ListPermReq) (*ListPermResp, error)
	// 设置用户角色
	SetUserRole(context.Context, *SetUserRoleReq) (*SetUserRoleResp, error)
	// 批量设置用户角色
	OverwriteUserRoles(context.Context, *OverwriteUserRolesReq) (*OverwriteUserRolesResp, error)
	// 设置角色
	SetRole(context.Context, *SetRoleReq) (*SetRoleResp, error)
	// 设置菜单
	SetPerm(context.Context, *SetPermReq) (*SetPermResp, error)
	// 移除用户角色
	RemoveUserRole(context.Context, *RemoveUserRoleReq) (*RemoveUserRoleResp, error)
	// 移除角色
	RemoveRole(context.Context, *RemoveRoleReq) (*RemoveRoleResp, error)
	// 移除菜单
	RemovePerm(context.Context, *RemovePermReq) (*RemovePermResp, error)
	mustEmbedUnimplementedRBACServer()
}

// UnimplementedRBACServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRBACServer struct{}

func (UnimplementedRBACServer) CheckPerm(context.Context, *CheckPermReq) (*CheckPermResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPerm not implemented")
}
func (UnimplementedRBACServer) ListUserRole(context.Context, *ListUserRoleReq) (*ListUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserRole not implemented")
}
func (UnimplementedRBACServer) ListRole(context.Context, *ListRoleReq) (*ListRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (UnimplementedRBACServer) ListPerm(context.Context, *ListPermReq) (*ListPermResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPerm not implemented")
}
func (UnimplementedRBACServer) SetUserRole(context.Context, *SetUserRoleReq) (*SetUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserRole not implemented")
}
func (UnimplementedRBACServer) OverwriteUserRoles(context.Context, *OverwriteUserRolesReq) (*OverwriteUserRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverwriteUserRoles not implemented")
}
func (UnimplementedRBACServer) SetRole(context.Context, *SetRoleReq) (*SetRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRole not implemented")
}
func (UnimplementedRBACServer) SetPerm(context.Context, *SetPermReq) (*SetPermResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPerm not implemented")
}
func (UnimplementedRBACServer) RemoveUserRole(context.Context, *RemoveUserRoleReq) (*RemoveUserRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserRole not implemented")
}
func (UnimplementedRBACServer) RemoveRole(context.Context, *RemoveRoleReq) (*RemoveRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRole not implemented")
}
func (UnimplementedRBACServer) RemovePerm(context.Context, *RemovePermReq) (*RemovePermResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePerm not implemented")
}
func (UnimplementedRBACServer) mustEmbedUnimplementedRBACServer() {}
func (UnimplementedRBACServer) testEmbeddedByValue()              {}

// UnsafeRBACServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RBACServer will
// result in compilation errors.
type UnsafeRBACServer interface {
	mustEmbedUnimplementedRBACServer()
}

func RegisterRBACServer(s grpc.ServiceRegistrar, srv RBACServer) {
	// If the following call pancis, it indicates UnimplementedRBACServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RBAC_ServiceDesc, srv)
}

func _RBAC_CheckPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).CheckPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_CheckPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).CheckPerm(ctx, req.(*CheckPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_ListUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).ListUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_ListUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).ListUserRole(ctx, req.(*ListUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_ListRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).ListRole(ctx, req.(*ListRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_ListPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).ListPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_ListPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).ListPerm(ctx, req.(*ListPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_SetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).SetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_SetUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).SetUserRole(ctx, req.(*SetUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_OverwriteUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverwriteUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).OverwriteUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_OverwriteUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).OverwriteUserRoles(ctx, req.(*OverwriteUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_SetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).SetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_SetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).SetRole(ctx, req.(*SetRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_SetPerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).SetPerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_SetPerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).SetPerm(ctx, req.(*SetPermReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_RemoveUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).RemoveUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_RemoveUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).RemoveUserRole(ctx, req.(*RemoveUserRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_RemoveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).RemoveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_RemoveRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).RemoveRole(ctx, req.(*RemoveRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RBAC_RemovePerm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePermReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RBACServer).RemovePerm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RBAC_RemovePerm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RBACServer).RemovePerm(ctx, req.(*RemovePermReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RBAC_ServiceDesc is the grpc.ServiceDesc for RBAC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RBAC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rbac.RBAC",
	HandlerType: (*RBACServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPerm",
			Handler:    _RBAC_CheckPerm_Handler,
		},
		{
			MethodName: "ListUserRole",
			Handler:    _RBAC_ListUserRole_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _RBAC_ListRole_Handler,
		},
		{
			MethodName: "ListPerm",
			Handler:    _RBAC_ListPerm_Handler,
		},
		{
			MethodName: "SetUserRole",
			Handler:    _RBAC_SetUserRole_Handler,
		},
		{
			MethodName: "OverwriteUserRoles",
			Handler:    _RBAC_OverwriteUserRoles_Handler,
		},
		{
			MethodName: "SetRole",
			Handler:    _RBAC_SetRole_Handler,
		},
		{
			MethodName: "SetPerm",
			Handler:    _RBAC_SetPerm_Handler,
		},
		{
			MethodName: "RemoveUserRole",
			Handler:    _RBAC_RemoveUserRole_Handler,
		},
		{
			MethodName: "RemoveRole",
			Handler:    _RBAC_RemoveRole_Handler,
		},
		{
			MethodName: "RemovePerm",
			Handler:    _RBAC_RemovePerm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rbac.proto",
}
