// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package rbac

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "rbac"
	EasymicroDiscoveryName = "rbac"
)

const EasymicroGRPCPbServiceNameRBAC = "rbac.RBAC"

var RBACDefault = &RBAC{}

func RBACGRPC() *RBAC {
	return RBACDefault
}

func NewRBACGRPC(dialOpts ...grpc.DialOption) *RBAC {
	return &RBAC{
		dialOpts: dialOpts,
	}
}

type RBAC struct {
	c        RBACClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *RBAC) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *RBAC) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameRBAC)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameRBAC, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewRBACClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *RBAC) CheckPerm(ctx context.Context, in *CheckPermReq, opts ...grpc.CallOption) (*CheckPermResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.CheckPerm(ctx, in, opts...)
}

func (s *RBAC) ListUserRole(ctx context.Context, in *ListUserRoleReq, opts ...grpc.CallOption) (*ListUserRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListUserRole(ctx, in, opts...)
}

func (s *RBAC) ListRole(ctx context.Context, in *ListRoleReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListRole(ctx, in, opts...)
}

func (s *RBAC) ListPerm(ctx context.Context, in *ListPermReq, opts ...grpc.CallOption) (*ListPermResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.ListPerm(ctx, in, opts...)
}

func (s *RBAC) SetUserRole(ctx context.Context, in *SetUserRoleReq, opts ...grpc.CallOption) (*SetUserRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetUserRole(ctx, in, opts...)
}

func (s *RBAC) OverwriteUserRoles(ctx context.Context, in *OverwriteUserRolesReq, opts ...grpc.CallOption) (*OverwriteUserRolesResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.OverwriteUserRoles(ctx, in, opts...)
}

func (s *RBAC) SetRole(ctx context.Context, in *SetRoleReq, opts ...grpc.CallOption) (*SetRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetRole(ctx, in, opts...)
}

func (s *RBAC) SetPerm(ctx context.Context, in *SetPermReq, opts ...grpc.CallOption) (*SetPermResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.SetPerm(ctx, in, opts...)
}

func (s *RBAC) RemoveUserRole(ctx context.Context, in *RemoveUserRoleReq, opts ...grpc.CallOption) (*RemoveUserRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.RemoveUserRole(ctx, in, opts...)
}

func (s *RBAC) RemoveRole(ctx context.Context, in *RemoveRoleReq, opts ...grpc.CallOption) (*RemoveRoleResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.RemoveRole(ctx, in, opts...)
}

func (s *RBAC) RemovePerm(ctx context.Context, in *RemovePermReq, opts ...grpc.CallOption) (*RemovePermResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.RemovePerm(ctx, in, opts...)
}
