// Code generated by protoc-gen-easymicro-jsonschema. DO NOT EDIT.
package main

import (
	"fmt"
	"log"

	"github.com/995933447/rbac/rbac"
	"github.com/995933447/runtimeutil"
	"github.com/invopop/jsonschema"
	jsoniter "github.com/json-iterator/go"
)

type ConfigSchemaOutput struct {
	Table         string             `json:"table"`
	IndexKeys     []string           `json: "index_keys"`
	UniqIndexKeys []string           `json:"uniq_index_keys"`
	JsonSchema    *jsonschema.Schema `json: "schema"`
}

func main() {
	jsonSchema := getJsonSchema()
	configSchemaOutput := &ConfigSchemaOutput{
		Table: rbac.UserRoleTbName,
		IndexKeys: []string{
			"scope",
			"role_id",
		},
		UniqIndexKeys: []string{
			"user_id,role_id",
		},
		JsonSchema: jsonSchema,
	}
	s, err := jsoniter.MarshalToString(configSchemaOutput)
	if err != nil {
		log.Fatal(runtimeutil.NewStackErr(err))
	}
	fmt.Print(s)
}

func getJsonSchema() *jsonschema.Schema {
	r := &jsonschema.Reflector{}
	r.DoNotReference = true
	r.AllowAdditionalProperties = true
	r.RequiredFromJSONSchemaTags = true
	r.FieldNameTag = "bson"
	return r.Reflect(&rbac.UserRoleOrm{})
}
